import AppShell from "@/components/AppShell";
import { trpc } from "@/lib/trpc";
import { Link } from "wouter";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, ImageOff, LoaderCircle, LockKeyhole, MessageCircle, Search, ShieldCheck, X } from "lucide-react";
import { useMemo, useState } from "react";

function factorLabel(score: number | null) { if (score === null) return "Unavailable"; if (score >= .95) return "Exact"; if (score >= .7) return "Strong"; if (score >= .45) return "Moderate"; return "Weak"; }
function formatDate(value: Date | string | null | undefined) { return value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "—"; }

export default function MatchesPage() {
  const query = trpc.matches.mine.useQuery();
  const [term, setTerm] = useState("");
  const [status, setStatus] = useState("all");
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const rows = query.data ?? [];
  const filtered = useMemo(() => rows.filter(item => { const haystack = `${item.lost?.itemName} ${item.found?.itemName} ${item.lost?.location} ${item.found?.location}`.toLowerCase(); return haystack.includes(term.toLowerCase()) && (status === "all" || item.status === status); }), [rows, term, status]);

  return <AppShell><div className="page-header"><div><p className="eyebrow">Signal review / live data</p><h1>Possible matches</h1><p>Every score below comes from comparing an actual lost report with an actual found report.</p></div><Link href="/dashboard" className="button button-secondary button-small"><ArrowLeft size={14} /> Overview</Link></div>
    <div className="matches-toolbar"><div className="search-wrap"><Search size={15} /><input className="search-input" value={term} onChange={e => setTerm(e.target.value)} placeholder="Search item, location, or brand" aria-label="Search matches" /></div><select className="filter-select" value={status} onChange={e => setStatus(e.target.value)} aria-label="Filter match status"><option value="all">All statuses</option><option value="possible">Possible</option><option value="contacted">Contacted</option><option value="recovered">Recovered</option><option value="not_match">Not a match</option></select></div>
    {query.isLoading ? <div className="loading-screen"><LoaderCircle size={20} className="spin" /></div> : filtered.length === 0 ? <div className="empty-state"><ImageOff size={24} /><strong>{rows.length ? "No matches fit that filter" : "No possible matches yet"}</strong><span>{rows.length ? "Try a different search or status." : "Report an item or load demo data to run the matching engine."}</span><Link href="/report/lost" className="button button-primary button-small" style={{ marginTop: 16 }}>Create a report <ArrowRight size={14} /></Link></div> : <div className="match-list">{filtered.map(item => <article className="match-card" key={item.id}><div className="match-thumb-pair"><img src={item.lost?.imageUrl} alt={`Lost ${item.lost?.itemName ?? "item"}`} /><img src={item.found?.imageUrl} alt={`Found ${item.found?.itemName ?? "item"}`} /></div><div className="match-card-main"><div className="match-card-top"><span className="match-status">Possible match</span><span className="mono">#{String(item.id).padStart(4, "0")}</span></div><h3>{item.lost?.itemName}</h3><p>{item.lost?.location} ↔ {item.found?.location} · {formatDate(item.createdAt)}</p><div className="match-reasons">{item.factors.filter((factor: any) => factor.score !== null && factor.score >= .55).slice(0, 3).map((factor: any) => <span className="reason-chip" key={factor.key}><Check size={10} /> {factor.label}: {factorLabel(factor.score)}</span>)}</div><div className="match-actions"><button className="button button-dark" onClick={() => setSelectedId(item.id)}>View details <ArrowRight size={12} /></button><button className="button button-secondary" onClick={() => setSelectedId(item.id)}><MessageCircle size={12} /> Contact</button></div></div><div className="score-block"><div><div className="score-number">{item.score}%</div><span className="score-label">Match score</span></div><div className="score-meter" aria-label={`${item.score}% match score`}><span style={{ width: `${item.score}%` }} /></div></div></article>)}</div>}
    {selectedId && <MatchModal id={selectedId} onClose={() => setSelectedId(null)} />}
  </AppShell>;
}

function MatchModal({ id, onClose }: { id: number; onClose: () => void }) {
  const detail = trpc.matches.get.useQuery({ id });
  const send = trpc.messages.send.useMutation();
  const utils = trpc.useUtils();
  const [body, setBody] = useState("");
  if (detail.isLoading || !detail.data) return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Loading match details"><div className="modal"><div className="loading-screen"><LoaderCircle size={22} className="spin" /></div></div></div>;
  const match = detail.data;
  const sendMessage = async (event: React.FormEvent) => { event.preventDefault(); if (!body.trim()) return; await send.mutateAsync({ matchId: id, body }); setBody(""); void utils.matches.get.invalidate({ id }); };
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="match-detail-title" onMouseDown={event => { if (event.currentTarget === event.target) onClose(); }}><div className="modal"><div className="modal-header"><div><p className="eyebrow" style={{ marginBottom: 4 }}>Match analysis / #{String(match.id).padStart(4, "0")}</p><h2 id="match-detail-title">{match.lost?.itemName}</h2></div><button className="icon-button" aria-label="Close details" onClick={onClose}><X size={17} /></button></div><div className="modal-body"><div className="modal-report-grid"><ReportDetail report={match.lost} type="LOST ITEM" /><ReportDetail report={match.found} type="FOUND ITEM" /></div><section className="analysis-card"><div style={{ display: "flex", justifyContent: "space-between", alignItems: "start", gap: 15 }}><div><p className="eyebrow" style={{ color: "#9bbeb0", marginBottom: 6 }}>AI match analysis</p><h3>Why this may be a match</h3></div><div className="score-number" style={{ color: "#ff9a70" }}>{match.score}%</div></div><p>{match.explanation}</p><div className="factor-grid">{match.factors.map((factor: any) => <div className="factor-row" key={factor.key}><span>{factor.label}</span><strong>{factorLabel(factor.score)}</strong><div className="factor-bar"><span style={{ width: `${factor.score === null ? 0 : Math.round(factor.score * 100)}%` }} /></div></div>)}</div><div style={{ marginTop: 16, display: "flex", alignItems: "center", gap: 7, color: "#9bbeb0", fontSize: 10 }}><ShieldCheck size={14} /> The score is a comparison signal, not a guaranteed probability.</div></section><section className="message-panel"><h3><LockKeyhole size={14} /> Contact safely</h3><p className="muted" style={{ fontSize: 10, margin: "-4px 0 10px" }}>Ask about a detail without exposing anyone’s phone or email.</p><div className="messages">{match.messages.length === 0 ? <span className="muted" style={{ fontSize: 10 }}>No messages yet. Start with a specific detail only the owner would know.</span> : match.messages.map(message => <div className={`message-bubble ${message.senderId === match.lost?.userId ? "mine" : ""}`} key={message.id}>{message.body}</div>)}</div><form className="message-compose" onSubmit={sendMessage}><input value={body} onChange={e => setBody(e.target.value)} placeholder="e.g. Can you describe the sticker?" aria-label="Message about this match" /><button className="button button-primary button-small" disabled={send.isPending}>{send.isPending ? <LoaderCircle size={13} className="spin" /> : <ArrowRight size={13} />}</button></form></section></div></div></div>;
}

function ReportDetail({ report, type }: { report: any; type: string }) { return <div className="report-detail-card"><img className="detail-image" src={report?.imageUrl} alt={`${type.toLowerCase()} photo of ${report?.itemName ?? "item"}`} /><div className="detail-type"><span className={`type-badge ${type.includes("LOST") ? "lost" : "found"}`}>{type}</span><span className="mono">{formatDate(report?.eventAt)}</span></div><h3>{report?.itemName}</h3><div className="detail-grid"><div><span>Category</span><strong>{report?.category}</strong></div><div><span>Color</span><strong>{report?.color || "Not provided"}</strong></div><div><span>Brand / model</span><strong>{[report?.brand, report?.model].filter(Boolean).join(" / ") || "Not provided"}</strong></div><div><span>Location</span><strong>{report?.location}</strong></div><div style={{ gridColumn: "1 / -1" }}><span>Description</span><strong>{report?.description}</strong></div><div style={{ gridColumn: "1 / -1" }}><span>Distinguishing features</span><strong>{report?.features || "Not provided"}</strong></div></div></div>; }
